[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9D3E9AF60>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/82ac7e9c42336ce1eb7fe23405a924bf
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9D329A5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/82ac7e9c42336ce1eb7fe23405a924bf
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9D3E9B2F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/82ac7e9c42336ce1eb7fe23405a924bf