[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9D3E9BEC0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9c76fea1499cdc61f9ca70ebfb1e9f0e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9D3E9B440>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9c76fea1499cdc61f9ca70ebfb1e9f0e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001D9D3E98F20>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9c76fea1499cdc61f9ca70ebfb1e9f0e