[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248EFC3DA30>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/efea2dac1b1a3a2529fb9290dfaf837a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248EFC3EA80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/efea2dac1b1a3a2529fb9290dfaf837a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248EFC3E5A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/efea2dac1b1a3a2529fb9290dfaf837a