[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248EFC3DBE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/707946cf4a049e01e3752a3a43ce3f74
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248EFBBE1B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/707946cf4a049e01e3752a3a43ce3f74
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248EFC3E240>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/707946cf4a049e01e3752a3a43ce3f74